# Site settings
title: Cahah&acute;
email: tom@lezotte.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/cahah" # the subpath of your site, e.g. /blog/
url: "http://tlezotte.github.io" # the base hostname & protocol for your site
twitter_username: tomlezotte
github_username:  tlezotte

# Build settings
markdown: kramdown
